Update and/or replace packages reported by cargo deny
error[unsound]: Unsoundness in `Error::downcast_mut()`
   ┌─ /workspace/Cargo.lock:14:1
   │
14 │ anyhow 1.0.86 registry+https://github.com/rust-lang/crates.io-index
   │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unsound advisory detected
   │
   ├ ID: RUSTSEC-2026-0190
   ├ Advisory: https://rustsec.org/advisories/RUSTSEC-2026-0190
   ├ Affected versions of this crate violate borrow rules, resulting in undefined behavior, when the user adds context to an error via `Error::context` and then later calls `Error::downcast_mut` on the returned `Error`.

     The flaw was corrected in commit `6e8c000` by revising how the mutable reference is constructed, avoiding inclusion of a shared reference in the resulting borrow chain.

     ## Example

     ```rust
     use anyhow::Error;
     use std::fmt;

     #[derive(Debug)]
     struct ErrorContext(&'static str);

     impl fmt::Display for ErrorContext {
         fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
             fmt::Display::fmt(&self.0, f)
         }
     }

     fn main() {
         let mut error = Error::msg("inner error").context(ErrorContext("old context"));
         let context: &mut ErrorContext = error.downcast_mut().unwrap();
         context.0 = "new context";
         println!("{:?}", error);
     }
     ```

     ## Miri output

     ```
     error: Undefined Behavior: trying to retag from <1538> for Unique permission at alloc602[0x38], but that tag only grants SharedReadOnly permission for this location
        --> src/ptr.rs:170:18
         |
     170 |         unsafe { &mut *self.ptr.as_ptr() }
         |                  ^^^^^^^^^^^^^^^^^^^^^^^ this error occurs as part of retag at alloc602[0x38..0x48]
         |
         = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
         = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
     help: <1538> was created by a SharedReadOnly retag at offsets [0x38..0x48]
        --> src/ptr.rs:89:18
         |
      89 |             ptr: NonNull::from(ptr),
         |                  ^^^^^^^^^^^^^^^^^^
         = note: stack backtrace:
                 0: anyhow::ptr::Mut::<'_, ErrorContext>::deref_mut
                     at src/ptr.rs:170:18: 170:41
                 1: anyhow::error::<impl anyhow::Error>::downcast_mut::<ErrorContext>
                     at src/error.rs:560:18: 560:46
                 2: main
                     at examples/downcast_mut.rs:15:38: 15:58
     ```
   ├ Announcement: https://github.com/dtolnay/anyhow/issues/451
   ├ Solution: Upgrade to >=1.0.103 (try `cargo update -p anyhow`)
   ├ anyhow v1.0.86
     ├── allo-isolate v0.1.26
     │   └── flutter_rust_bridge v2.14.0-beta.2
     ├── flutter_rust_bridge v2.14.0-beta.2 (*)
     └── flutter_rust_bridge_codegen v2.14.0-beta.2

error[unmaintained]: `derivative` is unmaintained; consider using an alternative
   ┌─ /workspace/Cargo.lock:51:1
   │
51 │ derivative 2.2.0 registry+https://github.com/rust-lang/crates.io-index
   │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
   │
   ├ ID: RUSTSEC-2024-0388
   ├ Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0388
   ├ The [`derivative`](https://crates.io/crates/derivative) crate is no longer maintained.
     Consider using any alternative, for instance:
     - [derive_more](https://crates.io/crates/derive_more)
     - [derive-where](https://crates.io/crates/derive-where)
     - [educe](https://crates.io/crates/educe)
   ├ Announcement: https://github.com/mcarton/rust-derivative/issues/117
   ├ Solution: No safe upgrade is available!
   ├ derivative v2.2.0
     └── flutter_rust_bridge_codegen v2.14.0-beta.2

error[unmaintained]: paste - no longer maintained
    ┌─ /workspace/Cargo.lock:123:1
    │
123 │ paste 1.0.14 registry+https://github.com/rust-lang/crates.io-index
    │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
    │
    ├ ID: RUSTSEC-2024-0436
    ├ Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0436
    ├ The creator of the crate `paste` has stated in the [`README.md`](https://github.com/dtolnay/paste/blob/master/README.md)
      that this project is not longer maintained as well as archived the repository

      ## Possible Alternative(s)

      - [`pastey`]: a fork of paste and is aimed to be a drop-in replacement with additional features for paste crate
      - [`with_builtin_macros`]: crate providing a [superset of `paste`'s functionality including general `macro_rules!` eager expansions](https://docs.rs/with_builtin_macros/0.1.0/with_builtin_macros/macro.with_eager_expansions.html)  and `concat!`/`concat_idents!` macros

      [`pastey`]: https://crates.io/crates/pastey
      [`with_builtin_macros`]: https://crates.io/crates/with_builtin_macros
    ├ Announcement: https://github.com/dtolnay/paste
    ├ Solution: No safe upgrade is available!
    ├ paste v1.0.14
      └── flutter_rust_bridge_codegen v2.14.0-beta.2

error[vulnerability]: Potential segfault in the time crate
    ┌─ /workspace/Cargo.lock:161:1
    │
161 │ time 0.1.45 registry+https://github.com/rust-lang/crates.io-index
    │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ security vulnerability detected
    │
    ├ ID: RUSTSEC-2020-0071
    ├ Advisory: https://rustsec.org/advisories/RUSTSEC-2020-0071
    ├ ### Impact

      The affected functions set environment variables without synchronization. On Unix-like operating systems, this can crash in multithreaded programs. Programs may segfault due to dereferencing a dangling pointer if an environment variable is read in a different thread than the affected functions. This may occur without the user's knowledge, notably in the Rust standard library or third-party libraries.

      The affected functions from time 0.2.7 through 0.2.22 are:

      - `time::UtcOffset::local_offset_at`
      - `time::UtcOffset::try_local_offset_at`
      - `time::UtcOffset::current_local_offset`
      - `time::UtcOffset::try_current_local_offset`
      - `time::OffsetDateTime::now_local`
      - `time::OffsetDateTime::try_now_local`

      The affected functions in time 0.1 (all versions) are:

      - `time::at_utc`
      - `time::at`
      - `time::now`
      - `time::tzset`

      Non-Unix targets (including Windows and wasm) are unaffected.

      ### Patches

      Pending a proper fix, the internal method that determines the local offset has been modified to always return `None` on the affected operating systems. This has the effect of returning an `Err` on the `try_*` methods and `UTC` on the non-`try_*` methods.

      Users and library authors with time in their dependency tree should perform `cargo update`, which will pull in the updated, unaffected code.

      Users of time 0.1 do not have a patch and should upgrade to an unaffected version: time 0.2.23 or greater or the 0.3 series.

      ### Workarounds

      A possible workaround for crates affected through the transitive dependency in `chrono`, is to avoid using the default `oldtime` feature dependency of the `chrono` crate by disabling its `default-features` and manually specifying the required features instead.

      #### Examples:

      `Cargo.toml`:

      ```toml
      chrono = { version = "0.4", default-features = false, features = ["serde"] }
      ```

      ```toml
      chrono = { version = "0.4.22", default-features = false, features = ["clock"] }
      ```

      Commandline:

      ```bash
      cargo add chrono --no-default-features -F clock
      ```

      Sources:
       - [chronotope/chrono#602 (comment)](https://github.com/chronotope/chrono/issues/602#issuecomment-1242149249)
       - [vityafx/serde-aux#21](https://github.com/vityafx/serde-aux/issues/21)
    ├ Announcement: https://github.com/time-rs/time/issues/293
    ├ Solution: Upgrade to >=0.2.23 (try `cargo update -p time`)
    ├ time v0.1.45
      └── chrono v0.4.26
          ├── fern v0.6.2
          │   └── flutter_rust_bridge_codegen v2.14.0-beta.2
          └── flutter_rust_bridge_codegen v2.14.0-beta.2 (*)

error[unsound]: Broadcast channel calls clone in parallel, but does not require `Sync`
    ┌─ /workspace/Cargo.lock:162:1
    │
162 │ tokio 1.34.0 registry+https://github.com/rust-lang/crates.io-index
    │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unsound advisory detected
    │
    ├ ID: RUSTSEC-2025-0023
    ├ Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0023
    ├ The broadcast channel internally calls `clone` on the stored value when
      receiving it, and only requires `T:Send`. This means that using the broadcast
      channel with values that are `Send` but not `Sync` can trigger unsoundness if
      the `clone` implementation makes use of the value being `!Sync`.

      Thank you to Austin Bonander for finding and reporting this issue.
    ├ Announcement: https://github.com/tokio-rs/tokio/pull/7232
    ├ Solution: Upgrade to >=1.38.2, <1.39.0 OR >=1.42.1, <1.43.0 OR >=1.43.1, <1.44.0 OR >=1.44.2 (try `cargo update -p tokio`)
    ├ tokio v1.34.0
      └── flutter_rust_bridge v2.14.0-beta.2

advisories FAILED, sources ok